### ISSUE TITLE
Understanding output and purging

### ISSUE THREAD

**Issue by malearimond** [shelkmike/Mabs#8]
Hello,
I'm using MABS to assemble several genomes sequenced with PacBio Hifi. Since the species I am looking at has a high variety in its mating system my genomes vary in their degree of heterozygosity as well. Before I used hifiasm v19 to assembly my genomes and decided depending on a certain degree of heterozygosity to purge or not to purge the assemblies (using the parameter -l0 implemented in hifiasm) since for the homozygous samples I could see that real duplicates were removed. So my first question would be, how does MABS deal with purging? Is the implemented purging of hifiasm always applied to the assembly or does MABS change the -l parameter of hifiasm as well?

Second, I have a question regarding the output files. I have several folders labelled as Assembly_for_point_[1-10]/ and AG_calculation_for_point_[1-10]/ , are those folders referring to the different assemblies generated and where can I find the AG calculation of my final assembly?

Thanks a lot for this nice tool and your help!

Best,
Male Arimond

**Comment by shelkmike** [comment]
Hi.

Mabs uses -l3. This is the default value in Hifiasm. But Mabs optimizes the value of "-s". If, during the optimization, Mabs comes to a value of -s close to 1, this will essentially mean that Mabs will not do haplotype purging.

During assembly, Mabs calculates AG for intermediate assemblies using a simplified method: instead of all reads, it aligns only reads that had matches to BUSCO proteins when aligned by DIAMOND. The calculation of AG for the final assembly might be more accurate if it is done using all reads. However, since the alignment of all reads is not very fast, Mabs, to save time, doesn't do this. So if you want to calculate AG for final contigs, you can run calculate_AG (the script calculate_AG.py) for them, giving all reads to calculate_AG.

**Comment by malearimond** [comment]
Ok, thanks a lot for the explanation!
Best,
Male
